//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenWhale.Extensions.TestStudio {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenWhale.Extensions.TestStudio.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 analysis complete! 的本地化字符串。
        /// </summary>
        public static string AnalysisComplete {
            get {
                return ResourceManager.GetString("AnalysisComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Tool 的本地化字符串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete? 的本地化字符串。
        /// </summary>
        public static string Are_You_Sure_Delete {
            get {
                return ResourceManager.GetString("Are You Sure Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 begin import file 的本地化字符串。
        /// </summary>
        public static string BeginImport {
            get {
                return ResourceManager.GetString("BeginImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 begin building  的本地化字符串。
        /// </summary>
        public static string BeiginBuild {
            get {
                return ResourceManager.GetString("BeiginBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building  的本地化字符串。
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 export success 的本地化字符串。
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 import complete! 的本地化字符串。
        /// </summary>
        public static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 input parameter is invalide! please define respond data 的本地化字符串。
        /// </summary>
        public static string input_parameter_is_invalide__please_define_respond_data {
            get {
                return ResourceManager.GetString("input parameter is invalide! please define respond data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 load script file is wrong or can not be anysis to script! 的本地化字符串。
        /// </summary>
        public static string load_script_file_is_wrong_or_can_not_be_anysis_to_script_ {
            get {
                return ResourceManager.GetString("load script file is wrong or can not be anysis to script!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please wait test complete before saving 的本地化字符串。
        /// </summary>
        public static string please_run_test_before_saving {
            get {
                return ResourceManager.GetString("please run test before saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LierdaTestStudio 的本地化字符串。
        /// </summary>
        public static string ProjectModel {
            get {
                return ResourceManager.GetString("ProjectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 script protocal|*.xml 的本地化字符串。
        /// </summary>
        public static string protocal_filter {
            get {
                return ResourceManager.GetString("protocal filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 script file is null can not be test 的本地化字符串。
        /// </summary>
        public static string script_file_is_null_can_not_be_test {
            get {
                return ResourceManager.GetString("script file is null can not be test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 test failed 的本地化字符串。
        /// </summary>
        public static string test_failed {
            get {
                return ResourceManager.GetString("test failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 test pass 的本地化字符串。
        /// </summary>
        public static string test_pass {
            get {
                return ResourceManager.GetString("test pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tips 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
    }
}
