//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenWhale.BootLoader.Implements.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenWhale.BootLoader.Implements.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 自动滚动 的本地化字符串。
        /// </summary>
        public static string auto_scroll {
            get {
                return ResourceManager.GetString("auto scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空所有 的本地化字符串。
        /// </summary>
        public static string clear_all_log {
            get {
                return ResourceManager.GetString("clear all log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空日志 的本地化字符串。
        /// </summary>
        public static string clear_log {
            get {
                return ResourceManager.GetString("clear log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示输出源 的本地化字符串。
        /// </summary>
        public static string display_output_source {
            get {
                return ResourceManager.GetString("display_output_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 换行 的本地化字符串。
        /// </summary>
        public static string new_line {
            get {
                return ResourceManager.GetString("new_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不换行 的本地化字符串。
        /// </summary>
        public static string not_new_line {
            get {
                return ResourceManager.GetString("not_new_line", resourceCulture);
            }
        }
    }
}
